Resources: 
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2
      InstanceType: t2.micro
  
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      Tags:
            - Key: Name
              Value: CF-Instance
      GroupDiscription: Creating security group
      SecurityGroupIngress:
        -CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
